### ISSUE TITLE
Spec for opcode Create&Create2

### ISSUE THREAD

**Issue by ChengYueJia** [privacy-scaling-explorations/zkevm-specs#333] opened 2022-12-06 07:30 UTC
If nobody works on this. I can try it.

**Comment by silathdiir** [comment] 2022-12-07 15:13
It seems that @z2trillion is working on the opcodes. Also @lispc

**Comment by CPerezz** [comment] 2023-02-03 08:54
Duplicate of #371

**Closed by CPerezz** 2023-02-03 08:54 UTC
