### ISSUE TITLE
Specify CREATE & CREATE2

### ISSUE THREAD

**Issue by aguzmant103** [privacy-scaling-explorations/zkevm-specs#371] opened 2023-02-02 12:45 UTC
Specify CREATE & CREATE2 execution states in the EVM circuit.
Sync with @z2trillion about https://github.com/privacy-scaling-explorations/zkevm-specs/pull/355

**Comment by ashWhiteHat** [comment] 2023-02-03 00:21
This seems duplicate of https://github.com/privacy-scaling-explorations/zkevm-specs/issues/333

**Comment by aguzmant103** [comment] 2023-03-02 12:41
@adria0

**Closed** 2023-04-20 08:02 UTC
